name: Publish compass-web to NPM and Docker Hub

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  publish-npm:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - name: Build compass-web
        run: |
          NODE_ENV=production npm run build
          NODE_ENV=production npm run build-server
      - name: Publish compass-web
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          TAG="${GITHUB_REF##*/v}"
          if [[ "$TAG" == *alpha* ]]; then
              npm publish --tag alpha --access public
          elif [[ "$TAG" == *beta* ]]; then
              npm publish --tag beta --access public
          elif [[ "$TAG" == *rc* ]]; then
              npm publish --tag rc --access public
          else
              npm publish --access public
          fi
  publish-docker:
    needs:
      - publish-npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get version from tag
        id: get-version-from-tag
        run: |
          version=${GITHUB_REF##*/v}
          echo "version=${version}"
          echo "version=${version}" >> $GITHUB_OUTPUT

          if [[ $version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "is_latest=true"
            echo "is_latest=true" >> $GITHUB_OUTPUT
          else
            echo "is_latest=false"
            echo "is_latest=false" >> $GITHUB_OUTPUT
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: haohanyang
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: haohanyang/compass-web:${{ steps.get-version-from-tag.outputs.version }}
          platforms: linux/amd64,linux/arm64

      - name: Build and push 1
        uses: docker/build-push-action@v6
        if: ${{ steps.get-version-from-tag.outputs.is_latest != 'true' }}
        with:
          push: true
          tags: haohanyang/compass-web-amd64:${{ steps.get-version-from-tag.outputs.version }}
          platforms: linux/amd64
          build-args: COMPASS_WEB_VERSION=${{ steps.get-version-from-tag.outputs.version }}

      - name: Build and push 2
        uses: docker/build-push-action@v6
        if: ${{ steps.get-version-from-tag.outputs.is_latest == 'true' }}
        with:
          push: true
          tags: haohanyang/compass-web-amd64:${{ steps.get-version-from-tag.outputs.version }},haohanyang/compass-web-amd64:latest
          platforms: linux/amd64
          build-args: COMPASS_WEB_VERSION=${{ steps.get-version-from-tag.outputs.version }}
